version: '3'

services:
  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - default

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    networks:
      - default

  web:
    build: .
    command: node dist/main.js
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb
    networks:
      - default

  nodejs_worker:
    build: .
    command: node dist/crawler.main.js
    depends_on:
      - redis
      - mongodb
    networks:
      - default

  python_worker:
    build: ./workers
    depends_on:
      - redis
      - mongodb
    networks:
      - default

  frontend:
    build: ./frontend
    ports:
      - "3030:80"
    depends_on:
      - web
    # expose:
    #   - 80
    labels:
      - "traefik.enable=true"
      # - "traefik.port=80"
      - "traefik.http.frontend.rule=Host(`chat.t99ltd.info`)"
      # - "providers.docker.network=ai-network"
      - "traefik.http.frontend.entrypoints=web"
      - "traefik.http.middlewares.frontend-redirect-web-secure.redirectscheme.scheme=https"
      - "traefik.http.frontend.middlewares=frontend-redirect-web-secure"
      - "traefik.http.frontend-secure.rule=Host(`chat.t99ltd.info`)"
      - "traefik.http.frontend-secure.entrypoints=websecure"
      - "traefik.http.frontend-secure.tls=true"
      - "traefik.http.frontend-secure.tls.certresolver=leresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - default
      - ai-network

networks:
  ai-network:
    external: true